---
name: Deploy packages on JFrog

on:
  push:
    branches:
      - develop

jobs:
  deploy_js_client:
    name: Deploy js client to jfrog and npmjs.com
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_deployment_npm.yml@mbr/reusable-workflow-jfrog-npm
    with:
      package_directory: "bitcoin_client_js"
